<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Rotating.Sonar.Client.Console</AssemblyName>
    <RootNamespace>Rotating.Sonar.Client.Console</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rotating.Sonar.Client.Visualizer\Rotating.Sonar.Client.Visualizer.csproj" />
    <ProjectReference Include="..\Rotating.Sonar.Client.Common\Rotating.Sonar.Client.Common.csproj" />
  </ItemGroup>


  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project> 